// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: filter.proto

package filter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED Operator = 0
	Operator_EQ                   Operator = 1
	Operator_CONTAINS             Operator = 2
	Operator_IN                   Operator = 3
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "EQ",
		2: "CONTAINS",
		3: "IN",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"EQ":                   1,
		"CONTAINS":             2,
		"IN":                   3,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_filter_proto_enumTypes[0].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_filter_proto_enumTypes[0]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_filter_proto_rawDescGZIP(), []int{0}
}

type ExprType int32

const (
	ExprType_EXPR_TYPE_UNSPECIFIED ExprType = 0
	ExprType_AND                   ExprType = 1
	ExprType_OR                    ExprType = 2
)

// Enum value maps for ExprType.
var (
	ExprType_name = map[int32]string{
		0: "EXPR_TYPE_UNSPECIFIED",
		1: "AND",
		2: "OR",
	}
	ExprType_value = map[string]int32{
		"EXPR_TYPE_UNSPECIFIED": 0,
		"AND":                   1,
		"OR":                    2,
	}
)

func (x ExprType) Enum() *ExprType {
	p := new(ExprType)
	*p = x
	return p
}

func (x ExprType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExprType) Descriptor() protoreflect.EnumDescriptor {
	return file_filter_proto_enumTypes[1].Descriptor()
}

func (ExprType) Type() protoreflect.EnumType {
	return &file_filter_proto_enumTypes[1]
}

func (x ExprType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExprType.Descriptor instead.
func (ExprType) EnumDescriptor() ([]byte, []int) {
	return file_filter_proto_rawDescGZIP(), []int{1}
}

type FilterCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op            Operator               `protobuf:"varint,2,opt,name=op,proto3,enum=filter.Operator" json:"op,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Values        []string               `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterCondition) Reset() {
	*x = FilterCondition{}
	mi := &file_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCondition) ProtoMessage() {}

func (x *FilterCondition) ProtoReflect() protoreflect.Message {
	mi := &file_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCondition.ProtoReflect.Descriptor instead.
func (*FilterCondition) Descriptor() ([]byte, []int) {
	return file_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FilterCondition) GetOp() Operator {
	if x != nil {
		return x.Op
	}
	return Operator_OPERATOR_UNSPECIFIED
}

func (x *FilterCondition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FilterCondition) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type FilterExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ExprType               `protobuf:"varint,1,opt,name=type,proto3,enum=filter.ExprType" json:"type,omitempty"`
	Conditions    []*FilterCondition     `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterExpr) Reset() {
	*x = FilterExpr{}
	mi := &file_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterExpr) ProtoMessage() {}

func (x *FilterExpr) ProtoReflect() protoreflect.Message {
	mi := &file_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterExpr.ProtoReflect.Descriptor instead.
func (*FilterExpr) Descriptor() ([]byte, []int) {
	return file_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FilterExpr) GetType() ExprType {
	if x != nil {
		return x.Type
	}
	return ExprType_EXPR_TYPE_UNSPECIFIED
}

func (x *FilterExpr) GetConditions() []*FilterCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type PagingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Page  uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Types that are valid to be assigned to FilteringType:
	//
	//	*PagingRequest_Query
	//	*PagingRequest_FilterExpr
	FilteringType isPagingRequest_FilteringType `protobuf_oneof:"filtering_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagingRequest) Reset() {
	*x = PagingRequest{}
	mi := &file_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagingRequest) ProtoMessage() {}

func (x *PagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagingRequest.ProtoReflect.Descriptor instead.
func (*PagingRequest) Descriptor() ([]byte, []int) {
	return file_filter_proto_rawDescGZIP(), []int{2}
}

func (x *PagingRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PagingRequest) GetFilteringType() isPagingRequest_FilteringType {
	if x != nil {
		return x.FilteringType
	}
	return nil
}

func (x *PagingRequest) GetQuery() string {
	if x != nil {
		if x, ok := x.FilteringType.(*PagingRequest_Query); ok {
			return x.Query
		}
	}
	return ""
}

func (x *PagingRequest) GetFilterExpr() *FilterExpr {
	if x != nil {
		if x, ok := x.FilteringType.(*PagingRequest_FilterExpr); ok {
			return x.FilterExpr
		}
	}
	return nil
}

type isPagingRequest_FilteringType interface {
	isPagingRequest_FilteringType()
}

type PagingRequest_Query struct {
	Query string `protobuf:"bytes,10,opt,name=query,proto3,oneof"`
}

type PagingRequest_FilterExpr struct {
	FilterExpr *FilterExpr `protobuf:"bytes,12,opt,name=filter_expr,json=filterExpr,proto3,oneof"`
}

func (*PagingRequest_Query) isPagingRequest_FilteringType() {}

func (*PagingRequest_FilterExpr) isPagingRequest_FilteringType() {}

var File_filter_proto protoreflect.FileDescriptor

const file_filter_proto_rawDesc = "" +
	"\n" +
	"\ffilter.proto\x12\x06filter\"w\n" +
	"\x0fFilterCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\x02op\x18\x02 \x01(\x0e2\x10.filter.OperatorR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06values\x18\x04 \x03(\tR\x06values\"k\n" +
	"\n" +
	"FilterExpr\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.filter.ExprTypeR\x04type\x127\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v2\x17.filter.FilterConditionR\n" +
	"conditions\"\x84\x01\n" +
	"\rPagingRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x16\n" +
	"\x05query\x18\n" +
	" \x01(\tH\x00R\x05query\x125\n" +
	"\vfilter_expr\x18\f \x01(\v2\x12.filter.FilterExprH\x00R\n" +
	"filterExprB\x10\n" +
	"\x0efiltering_type*B\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02EQ\x10\x01\x12\f\n" +
	"\bCONTAINS\x10\x02\x12\x06\n" +
	"\x02IN\x10\x03*6\n" +
	"\bExprType\x12\x19\n" +
	"\x15EXPR_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03AND\x10\x01\x12\x06\n" +
	"\x02OR\x10\x02B1Z/github.com/chnxq/xkitmod/testdata/filter;filterb\x06proto3"

var (
	file_filter_proto_rawDescOnce sync.Once
	file_filter_proto_rawDescData []byte
)

func file_filter_proto_rawDescGZIP() []byte {
	file_filter_proto_rawDescOnce.Do(func() {
		file_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filter_proto_rawDesc), len(file_filter_proto_rawDesc)))
	})
	return file_filter_proto_rawDescData
}

var file_filter_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_filter_proto_goTypes = []any{
	(Operator)(0),           // 0: filter.Operator
	(ExprType)(0),           // 1: filter.ExprType
	(*FilterCondition)(nil), // 2: filter.FilterCondition
	(*FilterExpr)(nil),      // 3: filter.FilterExpr
	(*PagingRequest)(nil),   // 4: filter.PagingRequest
}
var file_filter_proto_depIdxs = []int32{
	0, // 0: filter.FilterCondition.op:type_name -> filter.Operator
	1, // 1: filter.FilterExpr.type:type_name -> filter.ExprType
	2, // 2: filter.FilterExpr.conditions:type_name -> filter.FilterCondition
	3, // 3: filter.PagingRequest.filter_expr:type_name -> filter.FilterExpr
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_filter_proto_init() }
func file_filter_proto_init() {
	if File_filter_proto != nil {
		return
	}
	file_filter_proto_msgTypes[2].OneofWrappers = []any{
		(*PagingRequest_Query)(nil),
		(*PagingRequest_FilterExpr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filter_proto_rawDesc), len(file_filter_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filter_proto_goTypes,
		DependencyIndexes: file_filter_proto_depIdxs,
		EnumInfos:         file_filter_proto_enumTypes,
		MessageInfos:      file_filter_proto_msgTypes,
	}.Build()
	File_filter_proto = out.File
	file_filter_proto_goTypes = nil
	file_filter_proto_depIdxs = nil
}
